[package]
name = "ferrix-lib"
description = "A library for obtaining information about the software and hardware of a computer running Linux"
version = "0.4.3"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["ferrix", "hardware", "dmi", "smbios", "linux"]
categories = ["os"]

[dependencies]
anyhow.workspace = true
libc = { workspace = true, optional = true }
#futures = "0.3.31"
serde.workspace = true
serde_json.workspace = true
smbios-lib = { workspace = true, optional = true }
#tokio = { version = "1.46.1", features = ["full"] }
xml_serde.workspace = true
zbus = { workspace = true, optional = true }
zbus_systemd = { workspace = true, optional = true }

[features]
default = [
  "battery", "cpu", "desktop",
  "dmi", "drm", "firmware",
  "init", "mem", "net",
  "parts", "resources", "soft", "sensors",
  "sys", "cpu_freq", "vulnerabilities",
]

battery = []
cpu = []
cpu_freq = ["cpu"]
desktop = []
dmi = ["dep:smbios-lib"]
drm = []
firmware = []
init = ["dep:zbus", "dep:zbus_systemd"]
mem = []
net = []
parts = ["dep:libc"]
resources = []
sensors = []
soft = []
sys = []
vulnerabilities = ["cpu"]
