name: Build and attach binary packages to release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Prepare build environment
        run: |
          docker build -t fsm-builder -f ./Dockerfile . \
            && docker build -t fsm-rpm -f ./packaging/fedora/Dockerfile .

      - name: Build .deb packages (Debian 11)
        run: |
          mkdir -pv builds &&
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            fsm-builder packaging/debian/build.sh

      - name: Build .AppImage package (Debian 11)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            fsm-builder packaging/debian/appimage.sh

      - name: Build .rpm package (Fedora 42)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            fsm-rpm packaging/fedora/build.sh \
            -f ./packaging/fedora/Dockerfile

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-packages
          path: builds/*

      - name: Attach .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
